test8

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,17 +15,23 @@ jobs:
         with:
           fetch-depth: 0  # Fetch all history for all branches and tags
 
-      - name: Get release details
+           - name: Get release details
         id: get_release
         run: |
-          # Assuming you want to capture the release tag name
           RELEASE_TAG=$(echo "${{ github.ref }}" | sed -n 's/refs\/tags\/\(.*\)/\1/p')
           echo "Release tag: $RELEASE_TAG"
-          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV  # Pass this as an environment variable
+          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
 
       - name: Verify jq installation
         run: |
-          jq --version  # Remove this step if confident jq is installed
+          if ! command -v jq &> /dev/null; then
+            echo "jq could not be found, installing..."
+            sudo apt-get update && sudo apt-get install -y jq
+          fi
+
+      - name: Fetch main branch
+        run: |
+          git fetch origin main
 
       - name: Print git diff output
         run: |
@@ -34,18 +40,11 @@ jobs:
       - name: Detect changes
         id: detect
         run: |
-          # Fetch main branch for comparison
-          git fetch origin main
-          # Option A (assuming single line output): with a space after the dot
-          CHANGED_FUNCTIONS=$(git diff --name-only origin/main...$RELEASE_TAG | grep -E '\.py$|\.js$' | jq -r '.  | {name: basename(. // "-"), SrcFolder: dirname(. // "-")}';)
-          # Option B (alternative, each line represents a file path)
-          # CHANGED_FUNCTIONS=$(git diff --name-only origin/main...$RELEASE_TAG | grep -E '\.py$|\.js$' | jq -r '.[] | {name: basename(. // "-"), SrcFolder: dirname(. // "-")}';)
-          # Check if any changes were found
+          CHANGED_FUNCTIONS=$(git diff --name-only origin/main...$RELEASE_TAG | grep -E '\.py$|\.js$' | jq -R -s -c 'split("\n") | map(select(length > 0)) | map({name: (split("/") | last), SrcFolder: (split("/")[0:-1] | join("/"))})')
           if [ -z "$CHANGED_FUNCTIONS" ]; then
-            echo "changed-functions=[]" >> $GITHUB_ENV
-          else
-            echo "changed-functions=$CHANGED_FUNCTIONS" >> $GITHUB_ENV
+            CHANGED_FUNCTIONS='[]'
           fi
+          echo "changed-functions=$CHANGED_FUNCTIONS" >> $GITHUB_ENV
 
   deploy-production:
     needs: detect-changes
