storage

diff --git a/.github/workflows/sourcebuild.yml b/.github/workflows/sourcebuild.yml
--- a/.github/workflows/sourcebuild.yml
+++ b/.github/workflows/sourcebuild.yml
@@ -93,19 +93,19 @@ jobs:
       - name: Create Bucket
         id: check_bucket
         run: |
-          gcloud auth login  # Run this only if authentication is not set elsewhere
           PROJECT_ID=$(gcloud config get-value project)
           if [[ -z "$PROJECT_ID" ]]; then
-           echo "Error: No default project configured! Please set a project using:"
-           echo "  gcloud config set project relevate-dev-403605"
-          exit 1
+            echo "Error: No default project configured! Please set a project using:"
+            echo "  gcloud config set project relevate-dev-403605"
+            exit 1
           fi
           if [[ "$PROJECT_ID" != "relevate-dev-403605" ]]; then
-           echo "Warning: Using project '$PROJECT_ID'. Make sure it's correct."
+            echo "Warning: Using project '$PROJECT_ID'. Make sure it's correct."
           fi
           BUCKET_NAME="${{ matrix.function.TriggerName }}"
+          # Check bucket existence with exit code handling
           if ! gsutil ls -b gs://$BUCKET_NAME &> /dev/null; then
-            echo "Bucket $BUCKET_NAME does  not exist (or 'gsutil ls' failed)"
+            echo "Bucket $BUCKET_NAME does not exist (or 'gsutil ls' failed)"
             echo "Creating bucket $BUCKET_NAME"
             gcloud storage buckets create gs://$BUCKET_NAME \
                 --project $PROJECT_ID \
@@ -113,7 +113,6 @@ jobs:
           else
             echo "Bucket $BUCKET_NAME already exists"
           fi
-
 
       - name: Create Topic
         id: create_topic
